name       : data-default-instances-containers
version    : 0.0.1
release    : 3
source     :
    - https://hackage.haskell.org/package/data-default-instances-containers-0.0.1/data-default-instances-containers-0.0.1.tar.gz : a55e07af005c9815d82f3fc95e125db82994377c9f4a769428878701d4ec081a
license    : BSD-3-Clause
component  : programming.haskell
summary    : Default instances for types in containers
description: |
    Default instances for types in containers
builddeps  :
    - haskell-cabal-install
    - haskell-data-default-class-devel
rundeps    :
    - devel:
        - haskell-data-default-class-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
